CREATE DATABASE RetailLabDB;
GO

USE RetailLabDB;
GO

CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY IDENTITY(1,1),
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    Phone VARCHAR(20),
    City VARCHAR(50) DEFAULT 'Kathmandu',
    RegistrationDate DATE DEFAULT GETDATE()
);

-- Employees Table
CREATE TABLE Employees (
    EmployeeID INT PRIMARY KEY IDENTITY(1,1),
    FullName VARCHAR(100) NOT NULL,
    Position VARCHAR(50),
    Salary DECIMAL(10,2) CHECK (Salary > 10000),
    HireDate DATE
);

-- Products Table
CREATE TABLE Products (
    ProductID INT PRIMARY KEY IDENTITY(1,1),
    ProductName VARCHAR(100) NOT NULL,
    Category VARCHAR(50),
    Price DECIMAL(10,2) CHECK (Price > 0),
    StockQuantity INT CHECK (StockQuantity >= 0)
);

-- Orders Table
CREATE TABLE Orders (
    OrderID INT PRIMARY KEY IDENTITY(1,1),
    CustomerID INT,
    EmployeeID INT,
    OrderDate DATE DEFAULT GETDATE(),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID)
);

-- OrderDetails Table
CREATE TABLE OrderDetails (
    OrderDetailID INT PRIMARY KEY IDENTITY(1,1),
    OrderID INT,
    ProductID INT,
    Quantity INT CHECK (Quantity > 0),
    UnitPrice DECIMAL(10,2),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);


-- Insert Customers
INSERT INTO Customers (FullName, Email, Phone, City)
VALUES 
('Aarav Sharma', 'aarav@gmail.com', '9800000001', 'Kathmandu'),
('Sita Rai', 'sita@gmail.com', '9800000002', 'Lalitpur'),
('Ram Thapa', 'ram@gmail.com', '9800000003', 'Bhaktapur'),
('Nabin Karki', 'nabin@gmail.com', '9800000004', 'Kathmandu'),
('Priya Shrestha', 'priya@gmail.com', '9800000005', 'Pokhara');

-- Insert Employees
INSERT INTO Employees (FullName, Position, Salary, HireDate)
VALUES
('Ramesh Adhikari', 'Manager', 60000, '2021-01-10'),
('Sunita Lama', 'Sales Executive', 35000, '2022-05-12'),
('Bikash Gurung', 'Sales Executive', 32000, '2023-02-15'),
('Anita KC', 'Cashier', 25000, '2024-01-01');

-- Insert Products
INSERT INTO Products (ProductName, Category, Price, StockQuantity)
VALUES
('Laptop', 'Electronics', 80000, 10),
('Mobile', 'Electronics', 30000, 25),
('Headphones', 'Electronics', 2000, 50),
('Office Chair', 'Furniture', 7000, 15),
('Desk', 'Furniture', 12000, 5),
('Notebook', 'Stationery', 100, 200);

-- Insert Orders
INSERT INTO Orders (CustomerID, EmployeeID, OrderDate)
VALUES
(1, 2, '2025-01-10'),
(2, 3, '2025-01-12'),
(3, 2, '2025-02-01'),
(1, 1, '2025-02-10');

-- Insert OrderDetails
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, UnitPrice)
VALUES
(1, 1, 1, 80000),
(1, 3, 2, 2000),
(2, 2, 1, 30000),
(3, 4, 2, 7000),
(4, 6, 10, 100);

--Display all customers with their city and registration date.
select fullname, city, registrationdate 
from Customers;

--Display OrderID, Customer Name, Employee Name, and Order Date using appropriate joins.
select o.orderid, c.fullname as CustomerName, 
e.fullname as EmployeeName, o.orderdate
from orders o
inner join Customers c 
on o.CustomerID = c.CustomerID
inner join Employees e 
on o.EmployeeID = e.EmployeeID;

--Display Product Name, Category, Quantity, UnitPrice, and Total Price (Quantity × UnitPrice) for all order details.
select p.productname, p.category, od.quantity, od.Unitprice, Quantity * unitPrice as TotalPrice
from Products p 
join OrderDetails od
on p.productid = od. productid;


--Display customers who have never placed any orders.
select c.fullname, o.orderid 
from Customers c
left join orders o
on c.CustomerID= o.CustomerID
where o.orderid is null;

--Display products that have never been ordered.
select p.productname
from Products p
left join OrderDetails od
on p.ProductID= od.ProductID
where od.ProductID is null;

--Calculate total sales amount for each order.
select OrderId, sum(quantity * unitprice) as totalsales
from OrderDetails
group by orderID;

--Display total revenue generated by each employee.
select e.fullname, sum(od.quantity * od.unitprice) as revenue
from Employees e
join orders o 
on e.EmployeeID = o.EmployeeID
join OrderDetails od
on o.OrderId = od.OrderID
group by e.FullName;

--Display total quantity sold for each product in descending order.
select  p.productname, sum(od.quantity) as total
from Products p
left join OrderDetails od
on p.ProductID = od.productid
group by p.ProductName
order by total desc;

--Display the average salary grouped by Position.
select position, avg(salary) as avgsalary
from Employees 
group by position;

--Display total sales amount generated from each city.
select c.city, sum(od.quantity * od.unitprice) as totalsales
from customers c
join orders o 
on c.CustomerID = o.CustomerID
join OrderDetails od
on o.OrderID = od.OrderID
group by c.city;

--Display employees whose total sales amount is greater than 50,000 using HAVING clause.
select e.fullname, sum(od.quantity * od.unitprice) as totalsales
from employees e
join orders o 
on e.EmployeeID = o.EmployeeID
join OrderDetails od
on o.OrderID = od.orderid
group by e.fullname
having  sum(od.quantity * od.unitprice)> 50000;

--Display products whose total sold quantity is greater than 10 using HAVING clause.
select p.productName, sum(od.Quantity) as Qty
from Products p
join OrderDetails od 
on p.productid = od.productID
group by p.ProductName
having sum(od.Quantity) > 10;

--Find products whose price is higher than the average price of all products using a subquery.
select productname, price 
from products
where price > (select avg(price) from products);

--Display customers who placed more orders than the average number of orders per customer using a subquery.
select customerID
from orders
group by customerid
having count(*) >
(select avg(od) 
from (select count(*) as od 
      from orders
      group by customerID
    ) t
);

--Find the employee who generated the highest total revenue using a subquery.
SELECT TOP 1 e.FullName
FROM Employees e
JOIN Orders o ON e.EmployeeID = o.EmployeeID
JOIN OrderDetails od ON o.OrderID = od.OrderID
GROUP BY e.FullName
ORDER BY SUM(od.Quantity * od.UnitPrice) DESC;


--Display customer names in UPPERCASE and show only the first 3 characters of each name.
SELECT UPPER(FullName) AS Name,
LEFT(FullName,3) AS First3
FROM Customers;

--Display employees’ first name only (assume FullName contains first and last name separated by space).
SELECT LEFT(FullName, CHARINDEX(' ', FullName) - 1) AS FirstName
FROM Employees;

--Display customers whose name starts with the letter ‘A’.
SELECT FullName
FROM Customers
WHERE FullName LIKE 'A%';

--Display orders placed in the current month.
SELECT *
FROM Orders
WHERE MONTH(OrderDate) = MONTH(GETDATE())
AND YEAR(OrderDate) = YEAR(GETDATE());

--Display OrderID and number of days since the order was placed.
SELECT OrderID,
DATEDIFF(DAY, OrderDate, GETDATE()) AS DaysAgo
FROM Orders;

--Display employees hired in the last 2 years.
SELECT *
FROM Employees
WHERE HireDate >= DATEADD(YEAR,-2,GETDATE());

--Display month-wise total sales amount grouped by year and month.
SELECT YEAR(o.OrderDate) AS Year,
MONTH(o.OrderDate) AS Month,
SUM(od.Quantity*od.UnitPrice) AS Sales
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
GROUP BY YEAR(o.OrderDate), MONTH(o.OrderDate);

--Create a view named vw_OrderSummary that shows OrderID, Customer Name, Total Order Amount, and Order Date.
CREATE VIEW vw_OrderSummary AS
SELECT o.OrderID, c.FullName,
SUM(od.Quantity*od.UnitPrice) AS TotalAmount,
o.OrderDate
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
GROUP BY o.OrderID, c.FullName, o.OrderDate;

--Create a view named vw_EmployeeSales that shows Employee Name and Total Sales Amount.
CREATE VIEW vw_EmployeeSales AS
SELECT e.FullName,
SUM(od.Quantity*od.UnitPrice) AS TotalSales
FROM Employees e
JOIN Orders o ON e.EmployeeID = o.EmployeeID
JOIN OrderDetails od ON o.OrderID = od.OrderID
GROUP BY e.FullName;

--Create a view named vw_ProductSalesReport that shows Product Name, Category, Total Quantity Sold, and Total Revenue.
CREATE VIEW vw_ProductSalesReport AS
SELECT p.ProductName, p.Category,
SUM(od.Quantity) AS TotalQty,
SUM(od.Quantity*od.UnitPrice) AS Revenue
FROM Products p
JOIN OrderDetails od ON p.ProductID = od.ProductID
GROUP BY p.ProductName, p.Category;

--Display all records from vw_OrderSummary sorted by Total Order Amount in descending order.
SELECT *
FROM vw_OrderSummary
ORDER BY TotalAmount DESC;

--From vw_EmployeeSales, display employees whose total sales exceed 100,000.
SELECT *
FROM vw_EmployeeSales
WHERE TotalSales > 100000;

--From vw_ProductSalesReport, display products whose Total Revenue is greater than 20,000.
SELECT *
FROM vw_ProductSalesReport
WHERE Revenue > 20000;

--Generate a report showing Customer Name, Total Orders, Total Amount Spent, Last Order Date, and the Employee who handled their most recent order. Sort the result by Total Amount Spent in descending order.
SELECT 
c.FullName,
COUNT(o.OrderID) AS TotalOrders,
SUM(od.Quantity*od.UnitPrice) AS TotalSpent,
MAX(o.OrderDate) AS LastOrderDate,
(
    SELECT TOP 1 e.FullName
    FROM Orders o2
    JOIN Employees e ON o2.EmployeeID = e.EmployeeID
    WHERE o2.CustomerID = c.CustomerID
    ORDER BY o2.OrderDate DESC
) AS LastEmployee
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
GROUP BY c.CustomerID, c.FullName
ORDER BY TotalSpent DESC;